Prevent unsupported operand types error. (#20)
Drupal\views\Plugin\views\field\FieldPluginBase::advancedRender expects to have an alter array on fields that are added to the views output. If there is no alter array then the view will fatal with an error that looks like:

```
Error: Unsupported operand types in Drupal\views\Plugin\views\field\FieldPluginBase->advancedRender() (line 1174 of /app/docroot/core/modules/views/src/Plugin/views/field/FieldPluginBase.php)
```